blogapp/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import (
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)

# Create all urls here

urlpatterns = [
    path("", views.home, name='home'),

    path("register", views.register, name='register'),
    path("login", views.login_user, name='login'),
    path("logout", views.logout_user, name='logout'),

    path("create-blog", views.create_blog, name='create_blog'),
    path("blog-details/<int:id>", views.details_blog, name='details_blog'),
    path("update-blog/<int:id>", views.update_blog, name='update_blog'),
    path("delete-blog/<int:id>", views.delete_blog, name='delete_blog'),

    path('create-comment/<int:blog_id>', views.create_comment, name='create_comment'),

    path('approve-blog/<int:id>', views.approve_blog, name='approve-blog'),
    path('block-blog/<int:id>', views.block_blog, name='block-blog'),

    path('profile', views.profile, name = 'profile'),
    path('password-reset/',
         PasswordResetView.as_view(
             template_name='password_reset.html',
             html_email_template_name='password_reset_email.html' ),
         name='password-reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name='password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),
         name='password_reset_complete'),
]

blogger/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('blogapp.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blogapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, User

# # Create your models here.

class CustomUser(AbstractUser):
    profile_pic = models.ImageField(upload_to='img/profile/',null = True, blank = True)
    mobile = models.IntegerField(null = True, blank = True)

    def __str__(self):
        return self.first_name +" "+ self.last_name

class Blog(models.Model):
    PENDING = 'pending'
    APPROVED = 'approved'
    BLOCKED = 'blocked'

    STATUS_CHOICES = [
        (PENDING, 'Pending'),
        (APPROVED, 'Approved'),
        (BLOCKED, 'Blocked'),
    ]

    title = models.CharField(max_length=500)
    content = models.TextField()
    author = models.ForeignKey(CustomUser,on_delete=models.CASCADE)
    thumbnail = models.ImageField(upload_to='img/thumbnail/')
    status = models.CharField(max_length=20,choices=STATUS_CHOICES,default=PENDING)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title
    

class Comments(models.Model):
    commenter = models.ForeignKey(CustomUser,on_delete=models.CASCADE)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    comment = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.comment

class Notification(models.Model):
    user = models.ForeignKey(CustomUser,on_delete=models.CASCADE)
    notify = models.TextField()

    def __str__(self):
        return self.notify

templates/article.html
{% extends "base.html" %}
{% load static %}

{% block title %}Details{% endblock title %}

{% block content %}

<div class="container">
    <div class="jumbotron jumbotron-fluid mb-3 pl-0 pt-0 pb-0 bg-white position-relative">
        <div class="h-100 tofront">
            <div class="row justify-content-between">
                <div class="col-md-6 pt-6 pb-6 pr-6 align-self-center">
                    <p class="text-uppercase font-weight-bold">
                        <a class="text-danger" href="{% url "home" %}">Stories</a>
                    </p>
                    <h1 class="display-4 secondfont mb-3 font-weight-bold">{{blog.title}} </h1>
                    <p class="mb-3">
                        {{blog.content}}
                    </p>
                    <div class="d-flex align-items-center">
                        <img class="rounded-circle" src="{{blog.author}}" width="70">
                        <small class="ml-2">{{blog.author}} <span class="text-muted d-block">A few hours ago &middot; 5 min. read</span>
                        </small>
                    </div>
                </div>
                <div class="col-md-6 pr-0">
                    <img src="{{blog.thumbnail.url}}">
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End Header -->

<!--------------------------------------
MAIN
--------------------------------------->
<div class="container pt-4 pb-4">
    <div class="row justify-content-center">
        <div class="col-lg-2 pr-4 mb-4 col-md-12">
            <div class="sticky-top text-center">
                <div class="text-muted">
                    Share this
                </div>
                <div class="share d-inline-block">
                    <!-- AddToAny BEGIN -->
                    <div class="a2a_kit a2a_kit_size_32 a2a_default_style">
                        <a class="a2a_dd" href="https://www.addtoany.com/share"></a>
                        <a class="a2a_button_facebook"></a>
                        <a class="a2a_button_twitter"></a>
                    </div>
                    <script async src="https://static.addtoany.com/menu/page.js"></script>
                    <!-- AddToAny END -->
                </div>
            </div>
        </div>

        <div class="col-md-12 col-lg-8">
            <article class="article-post">
                <p>{{blog.content}}</p>
            </article>
            <div class="flex justify-between"
            {% if user == blog.author %}
            <div class="btn-group mb-2" role="group" aria-label="Basic example">
                <a type="button" href="{% url 'update_blog' blog.id %}" class="btn btn-info">Update</a>
                <a type="button" href="{% url 'delete_blog' blog.id %}" class="btn btn-danger" onclick="">Delete</a>
            </div>
            {% endif %}
            {% if user.is_superuser %}
            <div class="btn-group mb-2" role="group" aria-label="Basic example">
                <p><b>Status: </b>{{blog.status}}</p>
                <a type="button" href="{% url 'approve-blog' blog.id %}" class="btn btn-info">Approve</a>
                <a type="button" href="{% url 'block-blog' blog.id %}" class="btn btn-danger" onclick="">Block</a>
            </div>
            {% endif %}
            <div class="border p-5 bg-lightblue ">
                <form action="/create-comment/{{blog.id}}" method="post">
                    {%csrf_token%}
                    <input type="text" name="comment" id="" placeholder="Add Comments...">
                    <button type="submit">Create Command</button>
                </form>
                <h5 class="my-3">All Comments</h5>
                {% for comment in blog.comments_set.all %}
                <p class="mx-1 my-2 border-top border-gray">{{comment}}</p>
                {% endfor%}

            </div>
        </div>
    </div>
</div>

<div class="container pt-4 pb-4">
    <h5 class="font-weight-bold spanborder"><span>Read next</span></h5>
    <div class="row">
        <div class="col-lg-6">
            <div class="card border-0 mb-4 box-shadow h-xl-300">
                <div style="background-image: url(./assets/img/demo/3.jpg); height: 150px; background-size: cover; background-repeat: no-repeat;">
                </div>
                <div class="card-body px-0 pb-0 d-flex flex-column align-items-start">
                    <h2 class="h4 font-weight-bold">
                        <a class="text-dark" href="#">Brain Stimulation Relieves Depression Symptoms</a>
                    </h2>
                    <p class="card-text">
                        Researchers have found an effective target in the brain for electrical stimulation to improve
                        mood in people suffering from depression.
                    </p>
                    <div>
                        <small class="d-block"><a class="text-muted" href="./author.html">Favid Rick</a></small>
                        <small class="text-muted">Dec 12 · 5 min read</small>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-6">
            <div class="flex-md-row mb-4 box-shadow h-xl-300">
                <div class="mb-3 d-flex align-items-center">
                    <img height="80" src="./assets/img/demo/blog4.jpg">
                    <div class="pl-3">
                        <h2 class="mb-2 h6 font-weight-bold">
                            <a class="text-dark" href="./article.html">Nasa's IceSat space laser makes height maps of
                                Earth</a>
                        </h2>
                        <div class="card-text text-muted small">
                            Jake Bittle in LOVE/HATE
                        </div>
                        <small class="text-muted">Dec 12 · 5 min read</small>
                    </div>
                </div>
                <div class="mb-3 d-flex align-items-center">
                    <img height="80" src="./assets/img/demo/blog5.jpg">
                    <div class="pl-3">
                        <h2 class="mb-2 h6 font-weight-bold">
                            <a class="text-dark" href="./article.html">Underwater museum brings hope to Lake
                                Titicaca</a>
                        </h2>
                        <div class="card-text text-muted small">
                            Jake Bittle in LOVE/HATE
                        </div>
                        <small class="text-muted">Dec 12 · 5 min read</small>
                    </div>
                </div>
                <div class="mb-3 d-flex align-items-center">
                    <img height="80" src="./assets/img/demo/blog6.jpg">
                    <div class="pl-3">
                        <h2 class="mb-2 h6 font-weight-bold">
                            <a class="text-dark" href="./article.html">Sun-skimming probe starts calling home</a>
                        </h2>
                        <div class="card-text text-muted small">
                            Jake Bittle in LOVE/HATE
                        </div>
                        <small class="text-muted">Dec 12 · 5 min read</small>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End Main -->
{% endblock content %}
 

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <link rel="apple-touch-icon" sizes="76x76" href="{% static " assets/img/favicon.ico" %} "
    />
    <link rel=" icon" type="image/png" href="{% static " assets/img/favicon.ico" %} "/>
    <meta http-equiv=" X-UA-Compatible" content="IE=edge,chrome=1" />
  <title>Blogger | {% block title %}{% endblock title %}</title>
  <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no"
    name="viewport" />

  <!-- Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Playfair+Display:400,700|Source+Sans+Pro:400,700"
    rel="stylesheet" />
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css"
    integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous" />

  <!-- CSS -->
  <link href="{% static "assets/css/main.css" %}" rel="stylesheet" />
</head>

<body>

  <nav class="topnav navbar navbar-expand-lg navbar-light bg-white fixed-top">
    <div class="container">
      <a class="navbar-brand" href="./index.html"><strong>Mundana</strong></a>
      <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarColor02"
        aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="navbar-collapse collapse" id="navbarColor02" style="">
        <ul class="navbar-nav mr-auto d-flex align-items-center">
          <li class="nav-item">
            <a class="nav-link" href="./index.html">Intro <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="./article.html">Culture</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="./article.html">Tech</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="./article.html">Politics</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="./article.html">Health</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="./article.html">Collections</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="./about.html">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="./docs.html">Template <span class="badge badge-secondary">docs</span></a>
          </li>
        </ul>
        <ul class="navbar-nav ml-auto d-flex align-items-center">
          <li class="nav-item highlight">
            <a class="nav-link" href="https://www.wowthemes.net/mundana-free-html-bootstrap-template/">Get this
              Theme</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <!-- End Navbar -->


  <!--------------------------------------
  HEADER
  --------------------------------------->
  <div class="container">
    <div class="jumbotron jumbotron-fluid mb-3 pt-0 pb-0 bg-lightblue position-relative">
      <div class="pl-4 pr-0 h-100 tofront">
        <div class="row justify-content-between">
          <div class="col-md-6 pt-6 pb-6 align-self-center">
            <h1 class="secondfont mb-3 font-weight-bold">Mundana is an HTML Bootstrap Template for Professional Blogging
            </h1>
            <p class="mb-3">
              Beautifully crafted with the latest technologies, SASS & Bootstrap 4.1.3, Mundana is the perfect design
              for your professional blog. Homepage, post article and category layouts available.
            </p>
            <a href="./article.html" class="btn btn-dark">Read More</a>
          </div>
          <div class="col-md-6 d-none d-md-block pr-0"
            style="background-size:cover;background-image:url(./assets/img/demo/home.jpg);"> </div>
        </div>
      </div>
    </div>
  </div>
  <!-- End Header -->



  {% block content %}{% endblock content %}
  <!--------------------------------------
FOOTER
--------------------------------------->
  <div class="container mt-5">
    <footer class="bg-white border-top p-3 text-muted small">
      <div class="row align-items-center justify-content-between">
        <div>
          <span class="navbar-brand mr-2"><strong>Mundana</strong></span> Copyright &copy;
          <script>document.write(new Date().getFullYear())</script>
          . All rights reserved.
        </div>
        <div>
          Made with <a target="_blank" class="text-secondary font-weight-bold"
            href="https://www.wowthemes.net/mundana-free-html-bootstrap-template/">Mundana Theme</a> by WowThemes.net.
        </div>
      </div>
    </footer>
  </div>
  <!-- Javascript -->
  <script src="{% static "assets/js/vendor/jquery.min.js" %} "
      type=" text/javascript"></script>
  <script src="{% static "assets/js/vendor/popper.min.js" %}" type="text/javascript"></script>
  <script src="{% static "assets/js/vendor/bootstrap.min.js" %}" type="text/javascript"></script>
  <script src="{%static "assets/js/functions.js"%}" type="text/javascript"></script>
</body>

</html>

templates/category.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<link rel="apple-touch-icon" sizes="76x76" href="./assets/img/favicon.ico">
<link rel="icon" type="image/png" href="./assets/img/favicon.ico">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
<title>Mundana Template by WowThemesNet</title>
<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport'/>
<!-- Google Font -->
<link href="https://fonts.googleapis.com/css?family=Playfair+Display:400,700|Source+Sans+Pro:400,700" rel="stylesheet">
<!-- Font Awesome Icons -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
<!-- Main CSS -->
<link href="./assets/css/main.css" rel="stylesheet"/>
</head>
<body>
<!--------------------------------------
NAVBAR
--------------------------------------->
<nav class="topnav navbar navbar-expand-lg navbar-light bg-white fixed-top">
<div class="container">
	<a class="navbar-brand" href="./index.html"><strong>Mundana</strong></a>
	<button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
	<span class="navbar-toggler-icon"></span>
	</button>
	<div class="navbar-collapse collapse" id="navbarColor02" style="">
		<ul class="navbar-nav mr-auto d-flex align-items-center">
			<li class="nav-item">
			<a class="nav-link" href="./index.html">Intro <span class="sr-only">(current)</span></a>
			</li>
			<li class="nav-item">
			<a class="nav-link" href="./article.html">Culture</a>
			</li>
			<li class="nav-item">
			<a class="nav-link" href="./article.html">Tech</a>
			</li>
			<li class="nav-item">
			<a class="nav-link" href="./article.html">Politics</a>
			</li>
			<li class="nav-item">
			<a class="nav-link" href="./article.html">Health</a>
			</li>
			<li class="nav-item">
			<a class="nav-link" href="./article.html">Collections</a>
			</li>
			<li class="nav-item">
			<a class="nav-link" href="./about.html">About</a>
			</li>
			<li class="nav-item">
			<a class="nav-link" href="./docs.html">Template <span class="badge badge-secondary">docs</span></a>
			</li>
		</ul>
		<ul class="navbar-nav ml-auto d-flex align-items-center">
			<li class="nav-item highlight">
			<a class="nav-link" href="https://www.wowthemes.net/mundana-free-html-bootstrap-template/">Get this Theme</a>
			</li>
		</ul>
	</div>
</div>
</nav>
<!-- End Navbar -->
    
<!--------------------------------------
Main
--------------------------------------->
<div class="container mt-5 mb-5">
	<div class="row">
		<div class="col-md-8">
			<h5 class="font-weight-bold spanborder"><span>Featured in Science</span></h5>
			<div class="card border-0 mb-5 box-shadow">
				<div style="background-image: url(./assets/img/demo/1.jpg); height: 350px; background-size: cover; background-repeat: no-repeat;">
				</div>
				<div class="card-body px-0 pb-0 d-flex flex-column align-items-start">
					<h2 class="h2 font-weight-bold">
					<a class="text-dark" href="./article.html">Brain Stimulation Relieves Depression Symptoms</a>
					</h2>
					<p class="card-text">
						 Researchers have found an effective target in the brain for electrical stimulation to improve mood in people suffering from depression.
					</p>
					<div>
						<small class="d-block"><a class="text-muted" href="./author.html">Favid Rick</a></small>
						<small class="text-muted">Dec 12 · 5 min read</small>
					</div>
				</div>
			</div>
			<h5 class="font-weight-bold spanborder"><span>Latest</span></h5>
			<div class="mb-3 d-flex justify-content-between">
				<div class="pr-3">
					<h2 class="mb-1 h4 font-weight-bold">
					<a class="text-dark" href="./article.html">Nearly 200 Great Barrier Reef coral species also live in the deep sea</a>
					</h2>
					<p>
						 There are more coral species lurking in the deep ocean that previously thought.
					</p>
					<div class="card-text text-muted small">
						 Jake Bittle in SCIENCE
					</div>
					<small class="text-muted">Dec 12 · 5 min read</small>
				</div>
				<img height="120" src="./assets/img/demo/blog8.jpg">
			</div>
			<div class="mb-3 d-flex justify-content-between">
				<div class="pr-3">
					<h2 class="mb-1 h4 font-weight-bold">
					<a class="text-dark" href="./article.html">East Antarctica's glaciers are stirring</a>
					</h2>
					<p>
						 Nasa says it has detected the first signs of significant melting in a swathe of glaciers in East Antarctica.
					</p>
					<div class="card-text text-muted small">
						 Jake Bittle in SCIENCE
					</div>
					<small class="text-muted">Dec 12 · 5 min read</small>
				</div>
				<img height="120" src="./assets/img/demo/1.jpg">
			</div>
			<div class="mb-3 d-flex justify-content-between">
				<div class="pr-3">
					<h2 class="mb-1 h4 font-weight-bold">
					<a class="text-dark" href="./article.html">50 years ago, armadillos hinted that DNA wasn’t destiny</a>
					</h2>
					<p>
						 Nasa says it has detected the first signs of significant melting in a swathe of glaciers in East Antarctica.
					</p>
					<div class="card-text text-muted small">
						 Jake Bittle in SCIENCE
					</div>
					<small class="text-muted">Dec 12 · 5 min read</small>
				</div>
				<img height="120" src="./assets/img/demo/5.jpg">
			</div>
		</div>
		<div class="col-md-4 pl-4">
			<div class="sticky-top">
				<h5 class="font-weight-bold spanborder"><span>Popular in Science</span></h5>
				<ol class="list-featured">
					<li>
					<span>
					<h6 class="font-weight-bold">
					<a href="./article.html" class="text-dark">Did Supernovae Kill Off Large Ocean Animals?</a>
					</h6>
					<p class="text-muted">
						 Jake Bittle in SCIENCE
					</p>
					</span>
					</li>
					<li>
					<span>
					<h6 class="font-weight-bold">
					<a href="./article.html" class="text-dark">Humans Reversing Climate Clock: 50 Million Years</a>
					</h6>
					<p class="text-muted">
						 Jake Bittle in SCIENCE
					</p>
					</span>
					</li>
					<li>
					<span>
					<h6 class="font-weight-bold">
					<a href="./article.html" class="text-dark">Unprecedented Views of the Birth of Planets</a>
					</h6>
					<p class="text-muted">
						 Jake Bittle in SCIENCE
					</p>
					</span>
					</li>
					<li>
					<span>
					<h6 class="font-weight-bold">
					<a href="./article.html" class="text-dark">Effective New Target for Mood-Boosting Brain Stimulation Found</a>
					</h6>
					<p class="text-muted">
						 Jake Bittle in SCIENCE
					</p>
					</span>
					</li>
				</ol>
			</div>
		</div>
	</div>
</div>
    
<div class="container pt-4 pb-4">
	<div class="border p-5 bg-lightblue">
		<div class="row justify-content-between">
			<div class="col-md-6">
				<h5 class="font-weight-bold secondfont">Become a member</h5>
				 Get the latest news right in your inbox. It's free and you can unsubscribe at any time. We hate spam as much as we do, so we never spam!
			</div>
			<div class="col-md-6">
				<div class="row">
					<div class="col-md-6">
						<input type="text" class="form-control" placeholder="First name">
					</div>
					<div class="col-md-6">
						<input type="text" class="form-control" placeholder="Last name">
					</div>
					<div class="col-md-12 mt-3">
						<button type="submit" class="btn btn-success btn-block">Subscribe</button>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- End Main -->
    
<!--------------------------------------
FOOTER
--------------------------------------->
<div class="container mt-5">
	<footer class="bg-white border-top p-3 text-muted small">
	<div class="row align-items-center justify-content-between">
		<div>
			<span class="navbar-brand mr-2"><strong>Mundana</strong></span> Copyright &copy;
			<script>document.write(new Date().getFullYear())</script>
			 . All rights reserved.
		</div>
		<div>
			 Made with <a target="_blank" class="text-secondary font-weight-bold" href="https://www.wowthemes.net/mundana-free-html-bootstrap-template/">Mundana Theme</a> by WowThemes.net.
		</div>
	</div>
	</footer>
</div>
<!-- End Footer -->
    
<!--------------------------------------
JAVASCRIPTS
--------------------------------------->
<script src="./assets/js/vendor/jquery.min.js" type="text/javascript"></script>
<script src="./assets/js/vendor/popper.min.js" type="text/javascript"></script>
<script src="./assets/js/vendor/bootstrap.min.js" type="text/javascript"></script>
<script src="./assets/js/functions.js" type="text/javascript"></script>
</body>
</html>

templates/create_blog.html
{% extends "base.html" %}
{% load static %}

{% block content %}
{% if messages %}{{messages}}{% endif %}
<form action='/create-blog' method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Create Blog">
</form>
{% endblock content %}

templates/index.html
{% extends "base.html" %}
{% load static %}


{% block title %} Home {% endblock title %}
{% block content %}


<!--------------------------------------
MAIN
--------------------------------------->

<div class="container pt-4 pb-4">
    <div class="row">
        <div class="col-lg-6">
            <div class="card border-0 mb-4 box-shadow h-xl-300">
                <div style="background-image: url(./assets/img/demo/1.jpg); height: 150px;    background-size: cover;    background-repeat: no-repeat;"></div>
                <div class="card-body px-0 pb-0 d-flex flex-column align-items-start">
                    {% with blogs|first as blog %}
                    <h2 class="h4 font-weight-bold">
                        <a class="text-dark" href="{% url 'details_blog' blog.id %}">{{blog.title}}</a>
                    </h2>
                    <p class="card-text">
                        Researchers have found an effective target in the brain for electrical stimulation to improve
                        mood in people suffering from depression.
                    </p>
                    <div>
                        <small class="d-block"><a class="text-muted" href="">{{blog.author}}</a></small>
                        <small class="text-muted">Dec 12 &middot; 5 min read</small>
                    </div>
                    {% endwith %}
                </div>
            </div>
        </div>
        <div class="col-lg-6">
            <div class="flex-md-row mb-4 box-shadow h-xl-300">
                {% for blog in blogs|slice:"1:4"%}
                <div class="mb-3 d-flex align-items-center">
                    <img height="80" src="../media/{{ blog.thumbnail }}">
                    <div class="pl-3">
                        <h2 class="mb-2 h6 font-weight-bold">
                            <a class="text-dark" href="{% url 'details_blog' blog.id %}">{{blog.title}}</a>
                        </h2>
                        <div class="card-text text-muted small">
                            {{ blog.author }}
                        </div>
                        <small class="text-muted">Dec 12 &middot; 5 min read</small>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row justify-content-between">
        <div class="col-md-8">
            <h5 class="font-weight-bold spanborder"><span>All Stories</span></h5>
            {% for blog in blogs|slice:"4:7"%}

            <div class="mb-3 d-flex justify-content-between">
                <div class="pr-3">
                    <h2 class="mb-1 h4 font-weight-bold">
                        <a class="text-dark" href="{% url 'details_blog' blog.id %}">{{blog.title}}</a>
                    </h2>
                    <p>
                        There are more coral species lurking in the deep ocean that previously thought.
                    </p>
                    <div class="card-text text-muted small">
                        {{blog.author}}
                    </div>
                    <small class="text-muted">Dec 12 &middot; 5 min read</small>
                </div>
                <img height="120" src="../media/{{ blog.thumbnail }}" alt="{{blog.thumbnail}}">
            </div>
            {% endfor %}

            <div class="col-md-4 pl-4">
                <h5 class="font-weight-bold spanborder"><span>Popular</span></h5>
                <ol class="list-featured">
                    {% for blog in blogs|slice:"7:11"%}
                    <li>
				<span>
				<h6 class="font-weight-bold">
				<a href="{% url 'details_blog' blog.id %}" class="text-dark">{{blog.title}}</a>
				</h6>
				<p class="text-muted">
					{{blog.author}}
				</p>
				</span>
                    </li>
                    {%endfor%}

                </ol>
            </div>
        </div>
    </div>


    {% endblock content %}

    </body>
    </html>

templates/password_reset_complete.html
{%extends 'base.html'%}

{%block content%}

<div class="card center">
	<p>Your password has been changed successfully. Please <a href="{% url 'login' %}">Login</a></p>
</div>
 	
{%endblock content%}